name: pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened]

jobs:
    compile_scss:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: '0'
                  ref: ${{ github.head_ref }}

            - name: use node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '21.7.1'
                  check-latest: true

            - name: install dependencies
              run: npm i -g sass

            - name: compile scss
              run: node compile-scss.cjs

            - name: commit and push compiled CSS
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add -f '*.css'
                  git commit -m 'autocompile SCSS to CSS'
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    prettier:
        needs: [compile_scss]
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0

        - name: Prettier Action
          uses: creyD/prettier_action@v4.3
          with:
            prettier_options: --write **/*.{js,md,json,ts,tsx,css,scss,html,jsx}
            same_commit: true
            dry: false
            working_directory: './'
            only_changed: false
            clean_node_folder: true
            github_token: "${{ secrets.GITHUB_TOKEN }}"

    lint_test:
        needs: [prettier]
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: '0'

            - name: use node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '21.7.1'
                  check-latest: true

            - name: install dependencies
              run: npm ci

            - name: lint
              run: npm run lint

            - name: run tests
              run: npm run test
